"use client";

import React, { useState, useEffect, useCallback } from "react";
import { Pin, Image as ImageIcon, Bell, BellOff, X, FileText, Download, ScrollText } from "lucide-react";

interface TranscriptEntry {
  id: string;
  speakerName: string;
  text: string;
  createdAt: string;
}

interface Message {
  id: string;
  content: string;
  createdAt: string;
  isPinned?: boolean;
  profile?: {
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
  };
}

export function ChannelHeaderExtras({
  messages,
  channelId,
}: {
  messages: Message[];
  channelId?: string;
}) {
  const [drawer, setDrawer] = useState<"pinned" | "media" | "summary" | "transcript" | null>(null);
  const [isMuted, setIsMuted] = useState(false);
  const [serverPinnedMessages, setServerPinnedMessages] = useState<Message[]>([]);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [summaries, setSummaries] = useState<any[]>([]);
  const [summaryError, setSummaryError] = useState<string | null>(null);
  const [transcriptEntries, setTranscriptEntries] = useState<TranscriptEntry[]>([]);

  // 지금까지 쌓인(아직 요약 전) 자막 히스토리 조회
  const fetchTranscript = useCallback(async () => {
    if (!channelId) return;
    try {
      const res = await fetch(`/api/channels/${channelId}/transcript`);
      if (res.ok) {
        const data = await res.json();
        if (data.transcripts) setTranscriptEntries(data.transcripts);
      }
    } catch {}
  }, [channelId]);

  useEffect(() => {
    if (drawer !== "transcript") return;
    // eslint-disable-next-line react-hooks/set-state-in-effect -- fire-and-forget fetch, setState happens after await
    fetchTranscript();
    const timer = setInterval(fetchTranscript, 4000);
    return () => clearInterval(timer);
  }, [drawer, fetchTranscript]);

  const handleDownloadTranscript = () => {
    const lines = transcriptEntries.map(
      (e) => `[${new Date(e.createdAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}] ${e.speakerName}: ${e.text}`,
    );
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `transcript-${new Date().toISOString().slice(0, 19).replace(/:/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Fetch summary history from API
  const fetchSummaries = useCallback(async () => {
    if (!channelId) return;
    try {
      const res = await fetch(`/api/channels/${channelId}/summary`);
      if (res.ok) {
        const data = await res.json();
        if (data.summaries) setSummaries(data.summaries);
      }
    } catch {}
  }, [channelId]);

  useEffect(() => {
    if (drawer === "summary") {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- fire-and-forget fetch, setState happens after await
      fetchSummaries();
    }
  }, [drawer, fetchSummaries]);

  // PDF document export helper (TICK-307)
  const handleDownloadPDF = (summaryItem: { title: string; summaryText: string }) => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>${summaryItem.title}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; line-height: 1.6; color: #1e293b; }
            h1 { color: #6366f1; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
            .content { font-size: 14px; white-space: pre-wrap; background: #f8fafc; padding: 20px; border-radius: 10px; }
            .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <h1>📝 ${summaryItem.title}</h1>
          <div class="content">${summaryItem.summaryText}</div>
          <div class="footer">Generated by Omni Platform AI Summary Engine</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  // Manual AI summary trigger (TICK-306)
  const [generatingSummary, setGeneratingSummary] = useState(false);
  const handleGenerateSummary = async () => {
    if (!channelId) return;
    setGeneratingSummary(true);
    setSummaryError(null);
    try {
      const res = await fetch(`/api/channels/${channelId}/summary`, { method: "POST" });
      if (res.ok) {
        const data = await res.json();
        if (data.reason === "no_transcript") {
          setSummaryError("아직 쌓인 대화 자막이 없습니다. 통화 중 자막이 인식된 뒤에 다시 시도해 주세요.");
        } else {
          await fetchSummaries();
        }
      } else {
        const data = await res.json().catch(() => ({}));
        setSummaryError(data.error || "요약 생성에 실패했습니다.");
      }
    } catch {
      setSummaryError("요약 생성에 실패했습니다.");
    }
    setGeneratingSummary(false);
  };

  // Fetch pinned messages from API if channelId exists
  const fetchPinnedMessages = useCallback(async () => {
    if (!channelId) return;
    try {
      const res = await fetch(`/api/channels/${channelId}/pins`);
      if (res.ok) {
        const data = await res.json();
        setServerPinnedMessages(data);
      }
    } catch {
      // fallback
    }
  }, [channelId]);

  useEffect(() => {
    if (drawer === "pinned") {
      // eslint-disable-next-line react-hooks/set-state-in-effect -- fire-and-forget fetch, setState happens after await
      fetchPinnedMessages();
    }
  }, [drawer, fetchPinnedMessages]);

  // Combine local tagged messages (#pin/📌 or isPinned) and server pinned messages
  const localPinned = messages.filter(
    (m) => m.isPinned || m.content.includes("#pin") || m.content.includes("📌")
  );
  
  const pinnedMessagesMap = new Map<string, Message>();
  serverPinnedMessages.forEach((m) => pinnedMessagesMap.set(m.id, m));
  localPinned.forEach((m) => pinnedMessagesMap.set(m.id, m));
  const pinnedMessages = Array.from(pinnedMessagesMap.values());

  // Extract images from messages (![alt](url))
  const mediaItems: { url: string; sender: string; date: string }[] = [];
  messages.forEach((m) => {
    const match = m.content.match(/!\[.*?\]\((.*?)\)/);
    if (match && match[1]) {
      mediaItems.push({
        url: match[1],
        sender: m.profile?.displayName || m.profile?.username || "Unknown",
        date: new Date(m.createdAt).toLocaleDateString(),
      });
    }
  });

  return (
    <div className="relative flex items-center gap-1">
      {/* Pin Drawer Button */}
      <button
        onClick={() => setDrawer(drawer === "pinned" ? null : "pinned")}
        title="핀 고정 메시지 모아보기"
        className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${
          drawer === "pinned"
            ? "bg-idle/20 text-idle border border-idle/30"
            : "text-muted hover:bg-surface-2 hover:text-text"
        }`}
      >
        <Pin className="h-4 w-4" />
      </button>

      {/* Media Gallery Button */}
      <button
        onClick={() => setDrawer(drawer === "media" ? null : "media")}
        title="미디어 & 파일 갤러리"
        className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${
          drawer === "media"
            ? "bg-purple-500/20 text-purple-400 border border-purple-500/30"
            : "text-muted hover:bg-surface-2 hover:text-text"
        }`}
      >
        <ImageIcon className="h-4 w-4" />
      </button>

      {/* TICK-205: Summary Drawer Button */}
      <button
        onClick={() => setDrawer(drawer === "summary" ? null : "summary")}
        title="AI 회의록 요약 & 히스토리"
        className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${
          drawer === "summary"
            ? "bg-accent/20 text-accent border border-accent/30"
            : "text-muted hover:bg-surface-2 hover:text-text"
        }`}
      >
        <FileText className="h-4 w-4" />
      </button>

      {/* 실시간 자막 히스토리 & 추출 */}
      <button
        onClick={() => setDrawer(drawer === "transcript" ? null : "transcript")}
        title="자막 히스토리 전체보기 & 추출"
        className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${
          drawer === "transcript"
            ? "bg-idle/20 text-idle border border-idle/30"
            : "text-muted hover:bg-surface-2 hover:text-text"
        }`}
      >
        <ScrollText className="h-4 w-4" />
      </button>

      {/* Channel Notification Mute Toggle */}
      <button
        onClick={() => setIsMuted(!isMuted)}
        title={isMuted ? "채널 알림 켜기" : "채널 무음 (Mute)"}
        className={`flex h-8 w-8 items-center justify-center rounded-lg transition ${
          isMuted
            ? "bg-danger/20 text-danger border border-danger/30"
            : "text-muted hover:bg-surface-2 hover:text-text"
        }`}
      >
        {isMuted ? <BellOff className="h-4 w-4" /> : <Bell className="h-4 w-4" />}
      </button>

      {/* Drawer Overlay */}
      {drawer && (
        <div className="absolute top-10 right-0 w-80 rounded-2xl border border-line bg-surface p-4 shadow-2xl backdrop-blur-2xl z-50 text-left animate-fadeIn">
          <div className="flex items-center justify-between border-b border-line pb-2.5 mb-3">
            <span className="text-xs font-bold text-text flex items-center gap-1.5">
              {drawer === "pinned" && <Pin className="h-3.5 w-3.5 text-idle" />}
              {drawer === "media" && <ImageIcon className="h-3.5 w-3.5 text-purple-400" />}
              {drawer === "summary" && <FileText className="h-3.5 w-3.5 text-accent" />}
              {drawer === "transcript" && <ScrollText className="h-3.5 w-3.5 text-idle" />}
              {drawer === "pinned"
                ? "고정된 메시지 (Pin)"
                : drawer === "media"
                  ? "미디어 & 파일 갤러리"
                  : drawer === "summary"
                    ? "AI 회의록 요약"
                    : "실시간 자막 히스토리"}
            </span>
            <button onClick={() => setDrawer(null)} className="text-muted hover:text-text text-xs">
              <X className="h-4 w-4" />
            </button>
          </div>

          {drawer === "pinned" && (
            <div className="space-y-2 max-h-64 overflow-y-auto pr-1">
              {pinnedMessages.length === 0 ? (
                <div className="py-6 text-center text-xs text-muted">
                  <p>고정된 메시지가 없습니다.</p>
                  <p className="text-[10px] text-muted mt-1">메시지에 #pin 태그 또는 📌 이모지를 포함해 보세요.</p>
                </div>
              ) : (
                pinnedMessages.map((pm) => (
                  <div key={pm.id} className="rounded-xl border border-line bg-surface p-3 text-xs shadow-sm hover:border-idle/40 transition">
                    <div className="flex items-center justify-between text-muted text-[10px] mb-1">
                      <span className="font-semibold text-idle">@{pm.profile?.displayName || pm.profile?.username || "유저"}</span>
                      <span>{new Date(pm.createdAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</span>
                    </div>
                    <p className="text-text text-xs whitespace-pre-wrap leading-relaxed">{pm.content}</p>
                  </div>
                ))
              )}
            </div>
          )}

          {drawer === "media" && (
            <div className="max-h-64 overflow-y-auto pr-1">
              {mediaItems.length === 0 ? (
                <div className="py-6 text-center text-xs text-muted">
                  공유된 미디어가 없습니다.
                </div>
              ) : (
                <div className="grid grid-cols-2 gap-2">
                  {mediaItems.map((item, idx) => (
                    <div key={idx} className="group relative rounded-xl overflow-hidden border border-line bg-surface aspect-square">
                      <img src={item.url} alt="" className="h-full w-full object-cover transition group-hover:scale-105" />
                      <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 flex flex-col justify-end p-2 transition text-[10px] text-white">
                        <span className="font-semibold truncate">{item.sender}</span>
                        <span className="text-[9px] text-muted">{item.date}</span>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
          {drawer === "summary" && (
            <div className="space-y-3 max-h-64 overflow-y-auto pr-1">
              {/* TICK-306: Manual AI Summary Trigger Button */}
              <button
                onClick={handleGenerateSummary}
                disabled={generatingSummary}
                className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-xl bg-accent text-on-accent text-xs font-bold shadow-md hover:bg-accent-strong transition disabled:opacity-50"
              >
                <FileText className="h-3.5 w-3.5" />
                <span>{generatingSummary ? "AI 요약 생성 중..." : "✨ AI 회의록 즉시 생성"}</span>
              </button>

              {summaryError && (
                <div className="rounded-xl border border-danger/30 bg-danger/10 p-2.5 text-[11px] text-danger">
                  {summaryError}
                </div>
              )}

              {summaries.length === 0 ? (
                <div className="py-6 text-center text-xs text-muted">
                  생성된 요약 회의록이 없습니다. 위 버튼을 눌러 생성하세요.
                </div>
              ) : (
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                summaries.map((sum: any) => (
                  <div key={sum.id} className="rounded-xl border border-line bg-surface p-3 text-xs space-y-2">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-text truncate max-w-[140px]">{sum.title}</span>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => handleDownloadPDF(sum)}
                          title="PDF 내보내기"
                          className="flex items-center gap-0.5 px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 hover:bg-purple-500/30 text-[10px] font-bold transition"
                        >
                          <Download className="h-3 w-3" />
                          <span>PDF</span>
                        </button>
                      </div>
                    </div>
                    <p className="text-muted text-[11px] whitespace-pre-wrap leading-relaxed border-t border-line/50 pt-2">
                      {sum.summaryText}
                    </p>
                  </div>
                ))
              )}
            </div>
          )}

          {drawer === "transcript" && (
            <div className="space-y-2">
              <button
                onClick={handleDownloadTranscript}
                disabled={transcriptEntries.length === 0}
                className="w-full flex items-center justify-center gap-1.5 py-1.5 rounded-xl bg-idle/15 text-idle text-xs font-bold hover:bg-idle/25 transition disabled:opacity-50"
              >
                <Download className="h-3.5 w-3.5" />
                <span>대화 내용 추출 (.txt)</span>
              </button>

              <div className="space-y-1.5 max-h-64 overflow-y-auto pr-1">
                {transcriptEntries.length === 0 ? (
                  <div className="py-6 text-center text-xs text-muted">
                    아직 인식된 자막이 없습니다. 통화 중 말씀하시면 여기 쌓입니다.
                    <p className="text-[10px] mt-1">회의록 요약을 생성하면 이 목록은 비워지고 요약으로 남습니다.</p>
                  </div>
                ) : (
                  transcriptEntries.map((entry) => (
                    <div key={entry.id} className="rounded-lg bg-surface-2 px-2.5 py-1.5 text-[11px]">
                      <span className="font-bold text-idle">{entry.speakerName}</span>
                      <span className="text-muted ml-1.5">
                        {new Date(entry.createdAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}
                      </span>
                      <p className="text-text mt-0.5 leading-relaxed">{entry.text}</p>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
